name: Trigger Netlify Build
on:
  schedule:
    # runs “At 06:00.” ... so runs once a day now
    - cron: '0 6 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/65dd6126cfa6c075ba83ddf9
