name: Trigger Netlify Build
on:
  schedule:
    # runs “At minute 0 past hour 6, 12, 18, and 0.”
    - cron: '0 6,12,18,0 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/65dd6126cfa6c075ba83ddf9
